stages:
  - build
  - deploy-dev
  - deploy-stg
  - deploy-prod

variables:
  PROJECT_ID: prj-ecommerce-2024
  DOCKER_REGISTRY: me-central2-docker.pkg.dev
  IMAGE_NAME: docker/$CI_PROJECT_NAME
  IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_BRANCH}
  REGION: me-central2

.deploy: &deploy
  image:
    name: kiwigrid/gcloud-kubectl-helm:3.11.1-421.0.0-1
    entrypoint: [""]
  script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > /tmp/gcp_sa_key.json
    - gcloud auth activate-service-account --key-file=/tmp/gcp_sa_key.json
    - gcloud config set project $PROJECT_ID
    - gcloud auth configure-docker
    - gcloud container clusters get-credentials ${PROJECT_ID}-${CLUSTER_SUFFIX} --region $REGION --project $PROJECT_ID
    - cd deploy/$CI_PROJECT_NAME
    - >
      helm secrets upgrade --install ${CI_PROJECT_NAME}-${DEPLOY_ENV} . 
      -f values.yaml 
      -f helm_vars/${DEPLOY_ENV}/values.yaml 
      -f helm_vars/${DEPLOY_ENV}/secrets.yaml  
      -n ${CI_PROJECT_NAME}-${DEPLOY_ENV} 
      --set image.tag=${IMAGE_TAG} 
      --atomic 
      --timeout 300s
      --create-namespace

build:
  stage: build
  image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
  services:
    - docker:dind
  script:
    - docker pull $DOCKER_REGISTRY/$PROJECT_ID/$IMAGE_NAME:latest-${CI_COMMIT_BRANCH} || true
    - docker build -t $IMAGE_NAME . --cache-from $DOCKER_REGISTRY/$PROJECT_ID/$IMAGE_NAME:latest-${CI_COMMIT_BRANCH}
    - docker tag $IMAGE_NAME $DOCKER_REGISTRY/$PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG
    - docker tag $IMAGE_NAME $DOCKER_REGISTRY/$PROJECT_ID/$IMAGE_NAME:latest-${CI_COMMIT_BRANCH}
    - echo $GCLOUD_SERVICE_KEY | base64 -d > /tmp/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file=/tmp/gcloud-service-key.json
    - gcloud auth configure-docker $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG
    - docker push $DOCKER_REGISTRY/$PROJECT_ID/$IMAGE_NAME:latest-${CI_COMMIT_BRANCH}

deploy-dev:
  <<: *deploy
  stage: deploy-dev
  environment:
    name: dev
    url: https://${CI_PROJECT_NAME}-${DEPLOY_ENV}.dzrt.com
  variables:
    DEPLOY_ENV: dev
    CLUSTER_SUFFIX: dev
  needs:
    - build
  only:
    refs:
      - development

deploy-stg:
  <<: *deploy
  stage: deploy-stg
  environment:
    name: stg
    url: https://${CI_PROJECT_NAME}-${DEPLOY_ENV}.dzrt.com
  variables:
    DEPLOY_ENV: stg
    CLUSTER_SUFFIX: dev
  needs:
    - build
  only:
    refs:
      - staging
  when: manual

deploy-prod:
  <<: *deploy
  stage: deploy-prod
  environment:
    name: prod
    url: https://dzrt.com
  variables:
    DEPLOY_ENV: prod
    CLUSTER_SUFFIX: prod
  needs:
    - build
  only:
    refs:
      - main
  when: manual
