version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: medusa-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: medusa-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    container_name: medusa-redis
    restart: always
    ports:
      - "6389:6379"
    command: redis-server

  tolgee:
    image: tolgee/tolgee
    ports:
      - "8085:8080"
    volumes:
      - tolgee_data:/data

volumes:
  pgdata:
  tolgee_data:
