---
replicaCount: 1

image:
  repository: me-central2-docker.pkg.dev/prj-ecommerce-2024/docker/medusa
  pullPolicy: IfNotPresent
  tag: ""

env:
  TEST: 1

app:
  automigrate:
    enabled: true

service:
  type: NodePort
  port: 80
  container:
    port: 9000

ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.class: gce
  hosts:
    - host: XXXX.dzrt.com
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
   limits:
     cpu: 500m
     memory: 1500Mi
   requests:
     cpu: 500m
     memory: 1500Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: {}

affinity: {}
